name: 🐛 Bug Report
description: Thing are not working as expected. Thank you for submitting a bug report!
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve the Mentorship Guide!
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing. Feel free to include screenshots.
    validations:
      required: true
